[Pre-MAP Course Website](http://depts.washington.edu/premap/seminar/cohort-17-2021-seminar/) | [Pre-MAP GitHub](https://github.com/UWPreMAP/PreMAP2021) | [Google](https://www.google.com)

### Each time you access the PreMAP2021 directory make sure your files are up to date
1. Open up a terminal tab (New -> Terminal). Change directories into the PreMAP2021 directory, then do:
```bash
cd PreMAP2021
```
2. Update the directory to get any newly added files by running in the terminal:
```bash
git pull
```
3. Type in your terminal:
```bash
cd lessons
```
4. If you're on the AstroLab computer, type in your terminal:
```bash
jupyter notebook
```
This will open a webpage that has the lessons on them. You can select this lesson and then edit and run the cells to follow along with the lesson. Remember to change "Lastname" to your last name.

### Vocab for today
<ul><b>
    <li>package</li> - need to do math with lists
    <li>numpy</li>
    <li>function</li>
    <li>numpy array</li>
    <li>argument</li>
    </b>
</ul>

[Pre-MAP Course Website](http://depts.washington.edu/premap/seminar/cohort-17-2021-seminar/) | [Pre-MAP GitHub](https://github.com/UWPreMAP/PreMAP2021) | [Google](https://www.google.com)

# Python packages


We do specialized tasks in Python with <b>package</b>. A package is a collection of Python functions that someone wrote and bundled together for you to use. Some of the Python packages that we'll learn to use include: 

| Package | Uses                     |
|---------|--------------------------|
| `numpy` | Math with arrays (more on this below) | 
| `scipy` | A math toolkit built for use by scientists | 
| `matplotlib` | Visualization (plotting!) | 
| `astropy` | Astronomy-specific functions of all kinds | 

## Numpy - "num - pie"

Numpy is the most important package that we're going to teach you about, because it allows you to do calculations very quickly with Python. Below, we'll discover why it's useful.

*** 

Let's say you want to take the _sine_ or _cosine_ of an angle. There are numpy function that do this for you. 

To gain access to numpy's functions, you always need to do this command first: 
```python
import numpy as np
```
Run the line above in the cell below: 

In [1]:
import numpy as np #will see this a lot, np is a nickname for numpy

Now there's a _package_ stored in the variable called `np` that we can access anywhere in this notebook. There are <b>functions</b> for $\sin$ and $\cos$ that live within numpy. The way to access a function within a package is by calling the package name with a period after it, then the name of the function you want. So for $\sin$, you can do: 
```python
np.sin(0)
```
The `np.` part says "give me this function from numpy". The `sin()` part says "the function that I want to use is $\sin$", and the `0` is the angle that we want to take the $\sin$ of, in units of radians. Run that line in the cell below, and experiment with different angles. Try `np.cos` too.

In [2]:
np.cos(0)

1.0

In [3]:
np.cos(5)

0.28366218546322625

Numpy also has some built-in numbers that you might use. For example, $\pi$ is stored (to high precision!), in `np.pi`. Print out numpy's $\pi$ in the cell below: 

In [4]:
np.pi

3.141592653589793

In [5]:
angles = [0, np.pi / 2, np.pi, 3 * np.pi / 2, 2 * np.pi] #Quicker than individually typing out each function/operation b/c you are doing math on a whole list all at once.
print(angles) 

[0, 1.5707963267948966, 3.141592653589793, 4.71238898038469, 6.283185307179586]


Now let's say you had a list of angles, like `angles`$= [0, \pi/2, \pi, 3\pi/2, 2\pi]$. You could call `np.sin(angles[0])` to get the $\sin$ of the first angle, then `np.sin(angles[1])` on the second angle, etc. But that would be a really slow way to do it! 

### Arrays

The quick way is to create a <b>numpy array</b>. A numpy array is a vector or matrix of numbers, similar to the built in Python lists we saw in the last lesson. ```numpy``` can act on arrays more efficiently than Python can with ordinary lists.

Let's make a numpy array filled with the angles above:
```python
# First, here's the list that we want to have an array of: 
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

# Here's how we make a numpy array out of the list
angle_array = np.array(angle_list)
```
Write out those lines in the cell below. 

In [6]:
# First, here's the list that we want to have an array of: 
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

# Here's how we make a numpy array out of the list
angle_array = np.array(angle_list)
print(angle_array)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


Let's break down the command `np.array(angle_list)`. The `np.` says we're going to use a function from numpy, the `array()` says we're going to make an array out of the thing in the parentheses, and the `angle_list` is the _input_ or the <b>argument</b> of the function. 

In [7]:
angle_list
print(angle_list)
print(type(angle_list))
print(angle_list / 2) #It doesn't know how to apply the operation to the entire list.

[0, 1.5707963267948966, 3.141592653589793, 4.71238898038469, 6.283185307179586]
<class 'list'>


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
angle_list
print(angle_list)
print(type(angle_list))
print(angle_array / 2) #It doesn't know how to apply the operation to the entire list. #can just start with angle_array = np.array([0, np.pi, 2*nppi]) also you have to define angle_array & better to create variables.

In [ ]:
# You can treat an array as a list, but commands may change slightly. This gives you a new angle_array.
np.append(angle_array, 4 * np.pi)
print(angle_array)

#This gives you a modification of angle_array in place thus changing the ACTUAL variable.
angle_array = np.append(angle_array, 4 * np.pi)
print(angle_array)

### Example 1: Calculations with arrays

What is the $\sin$ and $\cos$ of each angle? Use the numpy array `angle_array` as the argument to the `np.sin` and `np.cos` functions in the cell below:

In [ ]:
np.sin(angle_array) #Ask researchers whether we really ARE working with tiny numbers.

Now you might be saying - wait a minute, $\sin(3\pi/2) = 0$, not $\approx$`1e-16`, what's that about? The short answer is - computers often get very very close to approximating the numbers that we actually want, but not all of the way there. You can get better precision if you tell the computer to use more memory. 

## More numpy commands

Now you can do things with the numpy array that you couldn't do with a Python list. Here are some of them, which you should experiment with in the cell below: 
```python
# Sum of all elements in the array:
angle_array.sum()

# Mean of all elements in the array:
angle_array.mean()

# Maximum of the elements in the array:
angle_array.max()

# Minimum of the elements in the array: 
angle_array.min()

# Standard deviation of the elements in the array: 
angle_array.std()
```
Try running each of the above commands one-by-one in the cell below to see what they output.

In [ ]:
print(angle_array)
print("/n")
print(angle_array.sum())

### Syntax Tips and Help ###
So what happens when you forget the name of a `numpy` function, or the how to use a particular function? `Jupyter` has some cool built-in features that you should take advantage of!

For example, say you forgot the name of the `sum` function -- you can type `np.` and then press `tab`, and you'll see that the notebook lists what functions are available in `numpy`! Spoiler alert, it's a loooong list since `numpy` has many functionalities. 

The point is you can use the `tab` tool (recall tab completion trick) to help you remember or recognize the function you're looking for. 

Just like how in `bash` environments you can read details on how to use a function with `man FUNCTIONNAME`, you can do that in `Python` as well. For example, say you forgot how to use the `np.sin` function -- you can type `np.sin?` + `Ctrl`+`return` and the notebook will return an inline window that tells you almost everything you need to know about the function. 

Try playing around with `np.` + `tab` and `np.cos?`, or any function with a `?` at the end, below. Tells you what the function from numpy does and you can also google it in better formatting (this is the manual).

In [ ]:
np.cos?



***

## Array arithmetic

There are lots of situations where you'll want to create a certain kind of array, and numpy has functions to help. 

You can make an array of consecutive integers from zero to nine with the function `np.arange`(arange is only in numpy):
```python
consecutive_integers = np.arange(10)
```
Just like with indexing to some endpoint, you tell python what number you want it to stop before.

In [8]:
consecutive_integers = np.arange(120)
print(consecutive_integers)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


Check it out, numpy did all the work for me, I didn't have to write down all the integers.

Now, this function is very flexible. You can give it 3 <b>arguments</b> instead of 1 and those 3 numbers will signify `np.arange(start, stop, step)`. For example, `np.arange(1, 9, 2)` would start at 1, stop before 9, with a step size of 2 (giving you every second number), so it would return `[1, 3, 5, 7]

In [10]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [11]:
np.arange(1,9,3)

array([1, 4, 7])

In [13]:
consecutive_integers = np.arange(10)
print(consecutive_integers)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
consecutive_integers[1:6:2] #same thing as np.arange(1,9,2)

array([1, 3, 5])

In [18]:
consecutive_integers[1::2] #give me everything starting at the second element and going forward and then there is not a zero in between the colons you just take everything that is the second element going forward.

array([1, 3, 5, 7, 9])

In the cell below, make an array with 10,000 sequential integers, starting with the zero. Save the array into a variable called `consecutive_integers`, and print it out:

In [26]:
consecutive_integers = np.arange(0,10000)
print(consecutive_integers)
print(len(consecutive_integers))

[   0    1    2 ... 9997 9998 9999]
10000


You'll see that numpy is polite. It knows you probably don't want to see all ten thousand integers, so it prints just the beginning and end of the array. 

### Exercise 2: Indexing/slicing numpy arrays
The same indexing and slicing rules that we learned for lists work on arrays. Keep in mind that arrays are indexed starting with 0, just like ```Python``` lists and when you give a range of indexes, it won't include the last one listed. In the cell below, print the 42nd element of the `consecutive_integers` array, and print the 101-103rd (inclusive) elements of the array. Remember that python starts counting at 0, so to get the first element of the array the index number should be 0:

In [27]:
print(consecutive_integers[41])
# Access the nth element with the (n-1)th index
# because python starts counting at 0

print(consecutive_integers[100:103])
# When indexing a range in python, you get up to the last element you asked for
# so, by putting 103 as our index, we're asking for everything
# up to the 104th element, which means our range ends with the 103rd element

41
[100 101 102]


Unlike lists, you can do arithmetic with numpy arrays. For example, if you had the following list: 

In [28]:
heights = [162, 185, 174, 191]
print(heights)

[162, 185, 174, 191]


And let's say you wanted to divide every element of the list by 2. 

In [29]:
heights / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Hey, that doesn't do what we wanted it to do!

You don't want to do math with python lists because they don't behave the way you would want a mathematical object to behave. This is what numpy arrays are for!

In [34]:
heights = [162, 185, 174, 191]
print(heights)
heights_array = np.array(heights)
print(heights_array)
heights_array / 2

[162, 185, 174, 191]
[162 185 174 191]


array([81. , 92.5, 87. , 95.5])

### Exercise 3: Array arithmetic

In the cell below: 
1. Create a variable called `heights_array`, which contains a numpy array of `heights` (using the `np.array` function we learned above)
2. Try adding, multiplying, subtracting, dividing, and exponentiating the array by 2
3. What happens if you try to add, multiply, subtract, divide, and exponentiate the python list, `heights`, by 2?

In [35]:
#DO THIS!

### Exercise 4: Inequalities
You can also evaluate inequalities with whole arrays at once. Find which values of the array above are greater than 180, store that result as an array and print it: 

In [37]:
print(3<5)
print(heights_array)

True
[162 185 174 191]


In [39]:
heights_array>180 #Numpy answers this question for every element

array([False,  True, False,  True])

In [41]:
heights_gt_180 = heights_array > 180 #Read box as heights greater than 180!
print(heights_gt_180)

[False  True False  True]


Notice - numpy arrays don't have to contain numbers (floats and integers). They can be _booleans_, and other things too!

Remember: a boolean is a special type with the value `True` or `False`.

In Exercise 4, you found that you can figure out which numbers in the array were greater than 180 all at once. It turns out, if you save that array of booleans: 

```python
heights_gt_180 = heights_array > 180
```

You can use `heights_gt_180` like a group of indices on `heights_array` to get just the heights where `heights_gt_180 == True`. 

In the cell below, try:
```python
heights_gt_180 = heights_array > 180
print(heights_array[heights_gt_180])
```
Did it print out the right indices? What if you flip the greater than to a less than? What if you try `==` instead?

In [46]:
#Finish

In [45]:
# Let's ask for heights less than 180
print(heights_array)
heights_lt_180 = heights_array<180
print(heights_lt_180)

[162 185 174 191]
[ True False  True False]


In [48]:
print(heights_array)
print(heights_gt_180)
print(heights_array[1], heights_array[3])

print(heights_array[heights_gt_180])
print(type(heights_array[heights_gt_180])) #So this is its own array!

[162 185 174 191]
[False  True False  True]
185 191
[185 191]
<class 'numpy.ndarray'>


## Putting it all together

Using all of these skills together, let's do something that we couldn't do easily with a scientific calculator. Let's find sum of all of the positive, even integers less than 10,000.

We'll do that in a few steps below: 

In [49]:
even_int = np.arange(0,10000,2)
print(even_int)

[   0    2    4 ... 9994 9996 9998]


In [50]:
even_int.sum()

24995000

In [51]:
total = np.sum(even_int)
print(total)

24995000


***

### Exercise 6

Using the above steps as a template, figure out the sum of the **odd** numbers less than **100,000**:

In [59]:
# Get all the numbers up to 100,000 in a numpy array (below is the easy way)
odd_int = np.arange(1,100000,2)
print(odd_int)
print(np.sum(odd_int))

[    1     3     5 ... 99995 99997 99999]
2500000000


In [58]:
numbers_100 = np.arange(0,100000)
print(numbers_100)
numbers_100 = np.array
print

[    0     1     2 ... 99997 99998 99999]


In [ ]:
# Now, we can get our boolean array
# Odd numbers have a remainder when divided by 2,
# The way to say this in python is: x % 2 != 0
# This says, x, when divided by 2 has a remainder that is not equal to 0

# Now we use bool_array_odds to index into numbers

# Then take the sum

numbers_100 

In [62]:
#Solution:
all_int = np.arange(10000)
print(all_int)
bool_odd_ints = all_int % 2 != 0 #!= means does not equal; and == says give me everything where the remainder IS equal to zero which gives you the even numbers
odd_int = all_int[bool_odd_ints]
print(np.sum(odd_int))




[   0    1    2 ... 9997 9998 9999]
25000000
